# Generated by Django 5.0.3 on 2024-03-13 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Painter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Anonymous', max_length=100)),
                ('period', models.CharField(choices=[('M', 'Medieval'), ('R', 'Renaissance'), ('B', 'Baroque'), ('U', 'Unknown')], default='U', max_length=1)),
            ],
        ),
    ]
