# Generated by Django 5.0.3 on 2024-03-20 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('painters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='painter',
            name='year_of_birth',
            field=models.CharField(default='Unknown', max_length=10),
        ),
        migrations.AddField(
            model_name='painter',
            name='year_of_death',
            field=models.CharField(default='Unknown', max_length=10),
        ),
    ]
