# Generated by Django 5.0.3 on 2024-03-20 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('painters', '0002_painter_year_of_birth_painter_year_of_death'),
    ]

    operations = [
        migrations.AlterField(
            model_name='painter',
            name='year_of_birth',
            field=models.IntegerField(default=9999, max_length=4),
        ),
        migrations.AlterField(
            model_name='painter',
            name='year_of_death',
            field=models.IntegerField(default=0, max_length=4),
        ),
    ]
