# Generated by Django 5.0.3 on 2024-03-27 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('painters', '0003_alter_painter_year_of_birth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='painter',
            name='year_of_birth',
            field=models.IntegerField(default=9999),
        ),
        migrations.AlterField(
            model_name='painter',
            name='year_of_death',
            field=models.IntegerField(default=0),
        ),
    ]
