# Generated by Django 5.0.3 on 2024-03-27 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paintings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='painting',
            name='on_loan',
            field=models.BooleanField(default=False),
        ),
    ]
